# The URL for the staticman API bridge endpoint
# You will want to modify some of the values:
#  ${github-username}: the username of the account with which you publish your blog
#  ${blog-repo}: the name of your blog repository in github
#  master: this the branch out of which your blog is published, often master or gh-pages
#  ${bridge_app_name}: the name you chose in Heroku for your bridge API
#  comments: the so-called property, this defines the key in staticman.yml where the configuration is found
#
# for me, this line reads:
# https://staticman-travisdownsio.herokuapp.com/v2/entry/travisdowns/travisdowns.github.io/master/comments
staticman_url: https://${bridge_app_name}.herokuapp.com/v2/entry/${github-username}/${blog-repo}/master/comments

# reCaptcha configuration info: the exact same site key and *encrypted* secret that you used in staticman.yml
# I personally don't think the secret needs to be included in the generated site, but the staticman API bridge uses
# it to ensure the site configuration and bridge configuration match (but why not just compare the site key?)
reCaptcha:
  siteKey: 6LcWstQUAAAAALoGBcmKsgCFbMQqkiGiEt361nK1
  secret: x3hQv+bPs/10Ovck9I4vJAVaE7bOA+TTp5ZDAkl9nOaFwM7K4zaUhsRck1v6SuJsg9PS8A3CxppTRN7d3lgg0RgY9EuRaMrpnNVh8przkFiiBSAPb9Asl3oyDp2cWXNDRzX9FZUy3pplzloGqaEsW0VOpgubPXLm42RvdyeVoA8/nsPYeVsMcYGh9fqWihfvdO2GKWqm56IS5QRyW5cjn3ti0yNHpTfnZXOIp54kkRlqoRHNTo+IoNA0eRmQsB3O76yDg78P4WMICJ0ByITTQlsbZjT6eL2Woo6awOly9oPgeTd5o/CSj5x99DMDK7xDvQ2KkK1pKr6V14A5hidy/SXIbvltTbJKiGlSzqMJAA5LitCuJNtWrQnIu7CG4YmWcSMuLj/rvmniWrCksD0ZY6Txn1FeQ0NICPoQ3otmZVfxXqcwvnwATcA/ftjx+lReMokb8ZeOWOvj8nBX/ciKUtD7K8h9Mf5BGNibvAtX+VenfsJkH75F6vsG4kdFR0oyg+EZxNC/7MIhlK03ukd0LrSNaD7On9gWpoEzbfhKLTKHxT7aqTmHRuaZSrEjWqHtDOI5DB86lzFjc5tpRkxcDg0oPyxvCg4R6h2VwNGnnhCTszljxdWlxztlcLsRBszqZHXK+QaCKeM0Xu4D++w5mZPOIIKgnkcuk2QyCA6uW7I=
