# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.


# blog info
title: Performance Matters
description: >- # this means to ignore newlines until "baseurl:"
  WikiSkills, Rethinking Education.
baseurl: / # the subpath of your site, e.g. /blog
url: "https://wikiskills.org"
permalink: /:categories/:year/:month/:day/:title:output_ext
google_analytics: UA-136594956-1

# me info
email: &email joe@joeczarnecki.com
author:
  name: Joe Czarnecki
  email: *email
  twitter: joeczar
twitter_username: joeczar
github_username:  joeczar

# Build settings
markdown: kramdown
theme: minima

# staticman (comments) configuration
staticman_url: https://https://staticman-axiomshift.herokuapp.com/v2/entry/staticBot/wikiSkills-blog/master/comments

reCaptcha:
  siteKey: 6LcWstQUAAAAALoGBcmKsgCFbMQqkiGiEt361nK1
  secret: x3hQv+bPs/10Ovck9I4vJAVaE7bOA+TTp5ZDAkl9nOaFwM7K4zaUhsRck1v6SuJsg9PS8A3CxppTRN7d3lgg0RgY9EuRaMrpnNVh8przkFiiBSAPb9Asl3oyDp2cWXNDRzX9FZUy3pplzloGqaEsW0VOpgubPXLm42RvdyeVoA8/nsPYeVsMcYGh9fqWihfvdO2GKWqm56IS5QRyW5cjn3ti0yNHpTfnZXOIp54kkRlqoRHNTo+IoNA0eRmQsB3O76yDg78P4WMICJ0ByITTQlsbZjT6eL2Woo6awOly9oPgeTd5o/CSj5x99DMDK7xDvQ2KkK1pKr6V14A5hidy/SXIbvltTbJKiGlSzqMJAA5LitCuJNtWrQnIu7CG4YmWcSMuLj/rvmniWrCksD0ZY6Txn1FeQ0NICPoQ3otmZVfxXqcwvnwATcA/ftjx+lReMokb8ZeOWOvj8nBX/ciKUtD7K8h9Mf5BGNibvAtX+VenfsJkH75F6vsG4kdFR0oyg+EZxNC/7MIhlK03ukd0LrSNaD7On9gWpoEzbfhKLTKHxT7aqTmHRuaZSrEjWqHtDOI5DB86lzFjc5tpRkxcDg0oPyxvCg4R6h2VwNGnnhCTszljxdWlxztlcLsRBszqZHXK+QaCKeM0Xu4D++w5mZPOIIKgnkcuk2QyCA6uW7I=


defaults:
  # Post defaults
  - scope:
      path: "_posts"
      type: posts
    values:
      comments: true

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/